version: "3"
services:
  backend:
    restart: on-failure
    build: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://john:pass@postgres:5432/john-doe-form
      NODE_ENV: development
      PORT: 3002
    ports:
      - "3002:3002"

  frontend:
    build: ./frontend
    ports:
      - "3000:4173"

  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: john-doe-form
