version: "3"
services:
  backend:
    restart: always
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://john:pass@postgres:5432/john-doe-form
      NODE_ENV: development
    ports:
      - "3002:3002"

  frontend:
    build: ./frontend
    ports:
      - "3000:4173"

  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: john-doe-form
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d john-doe-form -U john"]
      interval: 5s
      timeout: 10s
      retries: 120
